
POST http://localhost:8080/prompts/add
Content-Type: application/json

{
  "title": "My Title",
  "template": "My nice template"
}

###
GET http://localhost:8080/prompts

###
GET http://localhost:8080/prompts/4fb7d46d-9685-4a8c-94ed-25e15f1cb5a1
