# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake Linux

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "master", "develop"]

env:
  BUILD_TYPE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'Release' || 'Debug' }}
  HAS_GTEST: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'OFF' || 'ON' }}

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install pip
        run: sudo apt-get install -y python3-pip

      - name: Install conan
        run: pip install conan==1.59

      - name: Create build folder
        run: mkdir build

      - name: Create conan profile
        run: conan profile new --detect default

      - name: Updating default profile
        run: | 
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update settings.compiler.version=9.5 default

      - name: Install conan packages
        run: |
          cd build
          conan install .. --build=missing

      - name: Configure CMake
        run: cmake -DSERVER_PORT=8080 -DHAS_GTEST="${HAS_GTEST}"" -DVERSION="${VERSION:-1.0.0}" -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" ..

      - name: Run build
        run: cmake --build .
